host: example.com
port: 9090
endpoints:
  - path: /api/users
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Bearer token
  - path: /api/posts
    method: POST
    headers:
      Content-Type: application/json