import java.awt.*
import java.awt.geom.RoundRectangle2D
import javax.swing.*
import javax.swing.border.AbstractBorder
import javax.swing.border.EmptyBorder


fun main() {
    SwingUtilities.invokeLater {
        // 设置系统观感 (Look and Feel)，让默认组件尽量贴近系统
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
        } catch (e: Exception) { }

        // 创建一个模拟的父窗口
        val frame = JFrame("Main Window (Simulator)").apply {
            defaultCloseOperation = JFrame.EXIT_ON_CLOSE
            setSize(500, 300)
            layout = GridBagLayout()
            setLocationRelativeTo(null)
        }

        val btnTest = JButton("点击测试精细还原弹窗").apply {
            font = Font("SansSerif", Font.BOLD, 14)
            preferredSize = Dimension(220, 50)
            addActionListener {
                val parentWindow = SwingUtilities.getWindowAncestor(this)
                // 创建并显示弹窗
                val dialog = DeleteDialog(parentWindow)
                dialog.isVisible = true
            }
        }

        frame.add(btnTest)
        frame.isVisible = true
    }
}

// === 2. 精细还原的弹窗类 (DeleteDialog) ===
class DeleteDialog(parent: Window?) : JDialog(parent, "Confirmation", ModalityType.APPLICATION_MODAL) {

    // 精确提取的颜色值
    private val TOP_BAR_COLOR = Color(156, 92, 35)    // 顶部棕色条
    private val TITLE_COLOR = Color(0, 0, 0)          // 标题黑色
    private val TEXT_COLOR = Color(50, 50, 50)        // 正文深灰色
    private val BUTTON_DELETE_BG = Color(209, 73, 37) // Delete按钮红色背景
    private val BUTTON_LEAVE_BG = Color(235, 235, 235)// Leave按钮浅灰背景
    private val BUTTON_BORDER = Color(210, 210, 210)  // Leave按钮边框
    private val TEXT_AREA_BG = Color(248, 248, 248)   // 文本域背景
    private val TEXT_AREA_BORDER = Color(220, 220, 220)// 文本域边框
    private val FOOTER_BG = Color(242, 242, 242)      // 底部按钮栏背景

    // 字体设置
    private val TITLE_FONT = Font("SansSerif", Font.BOLD, 17)
    private val TEXT_FONT = Font("SansSerif", Font.PLAIN, 13)
    private val CODE_FONT = Font("Monospaced", Font.PLAIN, 12)

    init {
        isResizable = false
        // 去掉系统自带的标题栏，实现完全自定义（需要 Java 版本支持，在部分系统可能不生效）
        // isUndecorated = true
        // rootPane.windowDecorationStyle = JRootPane.NONE

        layout = BorderLayout()

        // --- 1. 顶部装饰条 (Brown Bar) ---
        val topBar = JPanel().apply {
            preferredSize = Dimension(0, 6) // 固定高度 6px
            background = TOP_BAR_COLOR
        }
        add(topBar, BorderLayout.NORTH)

        // --- 2. 主内容区 (Main Panel) ---
        val mainPanel = JPanel(GridBagLayout())
        mainPanel.background = Color.WHITE
        mainPanel.border = EmptyBorder(24, 24, 20, 24) // 增加内边距

        val gbc = GridBagConstraints()

        // 图标 (Grid x=0, y=0, height=3)
        gbc.gridx = 0
        gbc.gridy = 0
        gbc.gridheight = 3
        gbc.anchor = GridBagConstraints.NORTHWEST
        gbc.insets = Insets(2, 0, 0, 18) // 图标右侧间距

        // 获取系统错误图标，如果太小则放大
        var warningIcon = UIManager.getIcon("OptionPane.errorIcon")
        if (warningIcon != null && warningIcon.iconWidth < 40) {
            val img = (warningIcon as ImageIcon).image.getScaledInstance(48, 48, java.awt.Image.SCALE_SMOOTH)
            warningIcon = ImageIcon(img)
        }
        // 如果获取不到，使用一个后备的图标绘制
        mainPanel.add(JLabel(warningIcon ?: createFallbackIcon()), gbc)

        // 标题 (Grid x=1, y=0)
        gbc.gridx = 1
        gbc.gridy = 0
        gbc.gridheight = 1
        gbc.weightx = 1.0
        gbc.fill = GridBagConstraints.HORIZONTAL
        gbc.insets = Insets(0, 0, 12, 0) // 标题下方间距
        mainPanel.add(JLabel("Delete old temporary files?").apply {
            font = TITLE_FONT
            foreground = TITLE_COLOR
        }, gbc)

        // 描述文本 (Grid x=1, y=1)
        gbc.gridy = 1
        gbc.insets = Insets(0, 0, 16, 0) // 文本下方间距
        val msg = "<html><body style='width: 380px'>" + // 限制宽度以实现正确的换行
                "Your temporary directory contains the following folders which " +
                "appear to have been previously generated by Burp. Would you " +
                "like to delete these?<br><br>" +
                "Note: you should not delete these files if another instance of Burp " +
                "is currently running.</body></html>"
        mainPanel.add(JLabel(msg).apply {
            font = TEXT_FONT
            foreground = TEXT_COLOR
        }, gbc)

        // 圆角文本域 (Grid x=1, y=2)
        gbc.gridy = 2
        gbc.fill = GridBagConstraints.BOTH
        gbc.weighty = 1.0
        gbc.insets = Insets(0, 0, 4, 0)

        val textArea = JTextArea(
            "Thu Jan 15 14:57:26 CST 2026\n" +
                    "/var/folders/kc/02pcnt016f5dwqx1377p18fw0000gn/T/burp4978\n" +
                    "786791818774690.tmp"
        ).apply {
            font = CODE_FONT
            isEditable = false
            background = TEXT_AREA_BG
            foreground = TEXT_COLOR
            border = EmptyBorder(10, 10, 10, 10) // 文本域内部的 padding
            lineWrap = true
        }
        // 使用自定义圆角边框的 JScrollPane
        val scrollPane = JScrollPane(textArea).apply {
            border = RoundedBorder(8, TEXT_AREA_BORDER) // 8px 圆角
            preferredSize = Dimension(420, 86) // 固定大小
            verticalScrollBarPolicy = JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED
            horizontalScrollBarPolicy = JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
        }
        mainPanel.add(scrollPane, gbc)
        add(mainPanel, BorderLayout.CENTER)

        // --- 3. 底部按钮栏 (Footer) ---
        val buttonPanel = JPanel(FlowLayout(FlowLayout.RIGHT, 12, 0))
        buttonPanel.background = FOOTER_BG
        // 顶部有一条细灰线，底部和左右有 padding
        buttonPanel.border = BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(1, 0, 0, 0, Color(230, 230, 230)),
            EmptyBorder(12, 20, 12, 20)
        )

        // Leave 按钮 (灰色圆角)
        val btnLeave = RoundedButton("Leave").apply {
            bgNormal = BUTTON_LEAVE_BG
            fgNormal = TITLE_COLOR
            borderColor = BUTTON_BORDER
            preferredSize = Dimension(90, 32)
            addActionListener { dispose() }
        }

        // Delete 按钮 (红色圆角)
        val btnDelete = RoundedButton("Delete").apply {
            bgNormal = BUTTON_DELETE_BG
            fgNormal = Color.WHITE
            borderColor = BUTTON_DELETE_BG // 边框同色
            preferredSize = Dimension(90, 32)
            font = font.deriveFont(Font.BOLD) // 字体加粗
            addActionListener {
                println("Delete confirmed.")
                dispose()
            }
        }

        buttonPanel.add(btnLeave)
        buttonPanel.add(btnDelete)
        add(buttonPanel, BorderLayout.SOUTH)

        pack()
        setLocationRelativeTo(parent) // 居中
    }

    // 后备图标绘制
    private fun createFallbackIcon(): Icon {
        val size = 48
        val img = java.awt.image.BufferedImage(size, size, java.awt.image.BufferedImage.TYPE_INT_ARGB)
        val g = img.createGraphics()
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
        g.color = Color(180, 100, 50)
        g.fillOval(2,2, size-4, size-4)
        g.color = Color.WHITE
        g.font = Font("SansSerif", Font.BOLD, 32)
        g.drawString("!", 19, 36)
        g.dispose()
        return ImageIcon(img)
    }
}

// === 3. 自定义组件：圆角按钮 (RoundedButton) ===
class RoundedButton(text: String) : JButton(text) {
    var bgNormal: Color = Color.WHITE
    var fgNormal: Color = Color.BLACK
    var borderColor: Color = Color.LIGHT_GRAY
    private val radius = 6 // 圆角半径

    init {
        isOpaque = false // 必须设置为 false，否则背景会是方的
        isFocusPainted = false
        isContentAreaFilled = false
        border = EmptyBorder(5, 15, 5, 15) // 内部文字 padding
        font = Font("SansSerif", Font.PLAIN, 13)
    }

    override fun paintComponent(g: Graphics) {
        val g2 = g.create() as Graphics2D
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)

        // 绘制背景
        if (model.isPressed) {
            g2.color = bgNormal.darker()
        } else {
            g2.color = bgNormal
        }
        g2.fillRoundRect(0, 0, width - 1, height - 1, radius, radius)

        // 绘制边框
        g2.color = borderColor
        g2.drawRoundRect(0, 0, width - 1, height - 1, radius, radius)

        // 绘制文字
        super.paintComponent(g)
        g2.dispose()
    }

    override fun setForeground(fg: Color?) {
        super.setForeground(fg)
        if (fg != null) fgNormal = fg
    }
}

// === 4. 自定义组件：圆角边框 (RoundedBorder) ===
class RoundedBorder(private val radius: Int, private val color: Color) : AbstractBorder() {
    override fun paintBorder(c: Component, g: Graphics, x: Int, y: Int, width: Int, height: Int) {
        val g2 = g.create() as Graphics2D
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
        g2.color = color
        // 绘制圆角矩形边框
        g2.draw(RoundRectangle2D.Float(x.toFloat(), y.toFloat(), (width - 1).toFloat(), (height - 1).toFloat(), radius.toFloat(), radius.toFloat()))
        g2.dispose()
    }
    // 边框占据的空间
    override fun getBorderInsets(c: Component?): Insets = Insets(radius/2, radius/2, radius/2, radius/2)
    override fun getBorderInsets(c: Component?, insets: Insets): Insets {
        insets.set(radius/2, radius/2, radius/2, radius/2)
        return insets
    }
}